<?php
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$mac = $form->get('mac');
$mac->setAttribute('class', 'form-control');
$mac->setAttribute('placeholder', 'MAC Address');

// This provides a default CSS class and placeholder text for the artist element:
$ip = $form->get('ip');
$ip->setAttribute('class', 'form-control');
$ip->setAttribute('placeholder', 'IP Address');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('application', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($mac) ?>
    <?= $this->formElement($mac) ?>
    <?= $this->formElementErrors()->render($mac, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($ip) ?>
    <?= $this->formElement($ip) ?>
    <?= $this->formElementErrors()->render($ip, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();