<?php
// module/Terminal/view/terminal/terminal/edit.phtml:

$title = 'Edit terminal';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$mac = $form->get('mac');
$mac->setAttribute('class', 'form-control');
$mac->setAttribute('placeholder', 'Terminal title');

$ip = $form->get('ip');
$ip->setAttribute('class', 'form-control');
$ip->setAttribute('placeholder', 'Artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('application', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($mac) ?>
    <?= $this->formElement($mac) ?>
    <?= $this->formElementErrors()->render($mac, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($ip) ?>
    <?= $this->formElement($ip) ?>
    <?= $this->formElementErrors()->render($ip, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();